[build]
  publish = "."

[build.processing]
  skip_processing = false

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
